### PR TITLE
Fixing bug in clustering of lv grids.

### LINKED ISSUE #388: NullPointerException in `buildUniqueConnections`
When starting with sample grid:

```
java.lang.NullPointerException: Cannot invoke "org.jgrapht.GraphPath.getWeight()" because "path" is null
	at utils.Connections$.$anonfun$buildUniqueConnections$3(Connections.scala:223)
	at scala.collection.StrictOptimizedIterableOps.flatMap(StrictOptimizedIterableOps.scala:118)
	at scala.collection.StrictOptimizedIterableOps.flatMap$(StrictOptimizedIterableOps.scala:105)
	at scala.collection.convert.JavaCollectionWrappers$JSetWrapper.flatMap(JavaCollectionWrappers.scala:215)
	at utils.Connections$.$anonfun$buildUniqueConnections$2(Connections.scala:216)
	at scala.collection.immutable.List.flatMap(List.scala:294)
	at utils.Connections$.buildUniqueConnections(Connections.scala:215)
	at utils.Connections$.apply(Connections.scala:158)
	at utils.Clustering$.setup(Clustering.scala:142)
	at edu.ie3.osmogrid.lv.LvGridGeneratorSupport$.clusterLvGrids(LvGridGeneratorSupport.scala:220)
	at edu.ie3.osmogrid.lv.LvGridGeneratorSupport$.buildGrid(LvGridGeneratorSupport.scala:203)
	at edu.ie3.osmogrid.lv.LvGridGenerator$.$anonfun$idle$5(LvGridGenerator.scala:84)
	at scala.collection.immutable.List.map(List.scala:247)
	at scala.collection.immutable.List.map(List.scala:79)
	at edu.ie3.osmogrid.lv.LvGridGenerator$.$anonfun$idle$1(LvGridGenerator.scala:73)
	at org.apache.pekko.actor.typed.internal.BehaviorImpl$ReceiveBehavior.receive(BehaviorImpl.scala:146)
	at org.apache.pekko.actor.typed.Behavior$.interpret(Behavior.scala:283)
	at org.apache.pekko.actor.typed.Behavior$.interpretMessage(Behavior.scala:239)
	at org.apache.pekko.actor.typed.internal.adapter.ActorAdapter.handleMessage(ActorAdapter.scala:141)
	at org.apache.pekko.actor.typed.internal.adapter.ActorAdapter.aroundReceive(ActorAdapter.scala:117)
	at org.apache.pekko.actor.ActorCell.receiveMessage(ActorCell.scala:590)
	at org.apache.pekko.actor.ActorCell.invoke(ActorCell.scala:557)
	at org.apache.pekko.dispatch.Mailbox.processMailbox(Mailbox.scala:280)
	at org.apache.pekko.dispatch.Mailbox.run(Mailbox.scala:241)
	at org.apache.pekko.dispatch.Mailbox.exec(Mailbox.scala:253)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

First step would be finding out what causes this exception and how to fix it, or if the problem lies within the input data.

### PR DESCRIPTION
**Pull request by staudtMarius**
Resolves #388

### CODE REVIEW

File: src/main/scala/utils/Connections.scala [hunk 1]
```diff
@@ -205,40 +210,44 @@ object Connections {
...
-            )
+    val paths = vertexes.map { v => v -> shortestPath.getPaths(v) }.toMap
+
+    getAllUniqueCombinations(graph.vertexSet().asScala.toList).map {
+      case (nodeA, nodeB) =>
+        val path = paths(nodeA).getPath(nodeB)
+
+        if (path == null) {
+          val unconnected =
+            if (graph.edgesOf(nodeA).size() == 0) nodeA else nodeB
```
Comment (sebastian-peter) [inline src/main/scala/utils/Connections.scala:226]: I don't think we can say that - the unconnected node could still have edges to other nodes that are also unconnected to the other component of the graph. So I'd keep the error message more general, e.g.
"No path could be found between $nodeA and $nodeB, because either node is not connected to the graph."

File: src/main/scala/utils/Connections.scala [hunk 2]
```diff
@@ -187,15 +190,17 @@ object Connections {
...
     }
 
     Connections(elements, connectionMap.toMap, distanceMap ++ distanceMapAlt)
   }
 
-  /** Method for creating unique [[Connection]]s using a
-    * [[ShortestPathAlgorithm]].
+  /** Method for creating undirected [[Connection]]s using a
+    * [[ShortestPathAlgorithm]]. Excluding connections that have the same source
+    * and target vertex (loops) and duplicated connections.
```
Comment (sebastian-peter) [inline src/main/scala/utils/Connections.scala:202]: Found a better term:

```suggestion
    * and target vertex (loops) and bidirectional connections.
```

File: src/main/scala/utils/Connections.scala [hunk 3]
```diff
@@ -205,40 +210,44 @@ object Connections {
...
+          Quantities.getQuantity(path.getWeight, Units.METRE),
+          Some(path)
+        )
     }
   }
 
-  /** Method for creating unique [[Connection]]s.
-    *
+  /** Method for creating undirected [[Connection]]s. Excluding connections that
+    * have the same source and target vertex (loops) and duplicated connections.
```
Comment (sebastian-peter) [inline src/main/scala/utils/Connections.scala:242]:
```suggestion
    * have the same source and target vertex (loops) and bidirectional connections.
```

**Review by sebastian-peter — CHANGES_REQUESTED** [review]
Some quick remarks from my side

**Review by sebastian-peter — APPROVED** [review]
Thanks!
