### PR TITLE
Fixing some small bugs.

### LINKED ISSUE #397: Refactoring `SubGridHandling`
An improvement to the handling of subgrids in OSMoGrid.

### LINKED ISSUE #405: Fixing some small bugs that prevent OSMoGrid from running.
While trying out OSMoGrid, I found some small bugs.

### PR DESCRIPTION
**Pull request by staudtMarius**
Resolves #405
Resolves #397

### CODE REVIEW

**Comment by staudtMarius** [comment]
Found some more bugs. There is still one issue. After that one is resolved, OSMoGrid can generate valid lv and mv grids.

File: src/test/scala/edu/ie3/test/common/GridSupport.scala [hunk 1]
```diff
@@ -216,17 +260,27 @@ trait GridSupport {
     // include at least a single node for voltage level determination
     val dummyNodeA = new NodeInput(
       UUID.randomUUID(),
-      s"Dummy node in $subgridNo",
+      s"Dummy A node in $subgridNo",
```
Comment (danielfeismann) [inline src/test/scala/edu/ie3/test/common/GridSupport.scala:263]:
```suggestion
      s"Dummy nodeA in $subgridNo",
```

File: src/test/scala/edu/ie3/test/common/GridSupport.scala [hunk 2]
```diff
@@ -216,17 +260,27 @@ trait GridSupport {
...
       mock[Point],
       voltLvlA,
       subgridNo
     )
 
-    val dummyNodeB = new NodeInput(
+    val dummyNodeB1 = new NodeInput(
       UUID.randomUUID(),
-      s"Dummy node in $subgridNo",
+      s"Dummy B1 node in $subgridNo",
```
Comment (danielfeismann) [inline src/test/scala/edu/ie3/test/common/GridSupport.scala:273]:
```suggestion
      s"Dummy nodeB1 in $subgridNo",
```

File: src/test/scala/edu/ie3/test/common/GridSupport.scala [hunk 3]
```diff
@@ -216,17 +260,27 @@ trait GridSupport {
...
+      Quantities.getQuantity(1.0d, StandardUnits.TARGET_VOLTAGE_MAGNITUDE),
+      false,
+      mock[Point],
+      voltLvlB,
+      subgridNo
+    )
+
+    val dummyNodeB2 = new NodeInput(
+      UUID.randomUUID(),
+      s"Dummy B2 node in $subgridNo",
```
Comment (danielfeismann) [inline src/test/scala/edu/ie3/test/common/GridSupport.scala:283]:
```suggestion
      s"Dummy nodeB2 in $subgridNo",
```

File: src/main/scala/edu/ie3/osmogrid/guardian/run/RunGuardian.scala [hunk 4]
```diff
@@ -115,61 +115,82 @@ object RunGuardian
...
+            )
           )
         ) =>
       ctx.log.info(s"Received mv grids.")
 
       // mv coordinator is now allowed to die in peace
       childReferences.mvCoordinator.foreach(ctx.unwatch)
+      val updatedChildReferences = childReferences.copy(mvCoordinator = None)
+
+      // save sub grids if the should be put out
```
Comment (danielfeismann) [inline src/main/scala/edu/ie3/osmogrid/guardian/run/RunGuardian.scala:170]:
```suggestion
      // store sub grids if they should be put out
```

**Review by danielfeismann — COMMENTED** [review]
I only briefly checked this. Good work! some very minor suggestions from my side.

File: src/main/scala/edu/ie3/osmogrid/guardian/run/SubGridHandling.scala [hunk 5]
```diff
@@ -82,371 +103,236 @@ trait SubGridHandling {
...
     */
-  private def assignSubnetNumber(
-      subGrid: SubGridContainer,
-      subnetNumber: Int
-  ): Try[SubGridContainer] = Try {
-    val nodes = updateNodes(
-      subGrid.getRawGrid.getNodes.asScala.toSeq,
-      subnetNumber
-    )
+  private def assignSubNetNumbers(
```
Comment (danielfeismann) [inline src/main/scala/edu/ie3/osmogrid/guardian/run/SubGridHandling.scala:232]: I opt to change this method name since there is already one method assignSubNetNumbers doing other things.

File: src/main/scala/edu/ie3/osmogrid/lv/LvGridGeneratorSupport.scala [hunk 6]
```diff
@@ -192,17 +194,33 @@ object LvGridGeneratorSupport extends LazyLogging {
       lineInputs,
       gridName,
       loadSimultaneousFactor,
-      ratedVoltageMv,
+      mvVoltage,
       transformer2WTypeInput
     )
   }
 
+  /** Method for clustering lv grids.
```
Comment (danielfeismann) [inline src/main/scala/edu/ie3/osmogrid/lv/LvGridGeneratorSupport.scala:202]: Great, that you enhance the ScalaDocs as well!

**Review by danielfeismann — CHANGES_REQUESTED** [review]
Almost there, should be the last issues from my side.

**Review by danielfeismann — APPROVED** [review]
Great, that you fixed these bugs. Thanks!
